export const OBSERVED_DIRECTORIES = 'OBSERVED_DIRECTORIES'
export const SONG_EXTENDED_METADATA = 'SONG_EXTENDED_METADATA'
export const PLAYBACK_HISTORY = 'PLAYBACK_HISTORY'

// Deprecations
export const DEPRECATED_LOCAL_STORAGE_KEYS = ['SONG_DATA', 'UPLOADS/SONG_LIST']
